[project]
name = "dot-utils"
version = "0.1.0"
description = "Testing environment for scripts inside my dotfiles"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
